use better shebang for bash scripts
the shebang "#!/usr/bin/env bash" will be able to find bash if it's in a
user's path, not jsut at "/bin/bash"

diff --git a/scripts/.local/bin/install_pkgs b/scripts/.local/bin/install_pkgs
--- a/scripts/.local/bin/install_pkgs
+++ b/scripts/.local/bin/install_pkgs
@@ -1,4 +1,5 @@
-#!/bin/bash
+#!/usr/bin/env bash
+
 MY_OS=0
 
 detect_os() {
@@ -76,6 +77,11 @@ install_from_pkg_file(){
 				exit 1
 			fi
 		elif [[ "$MY_OS" == "2" ]]; then
+			if ! command -v brew &> /dev/null; then
+				echo "brew not found, install brew first (sorry)"
+				echo "https://brew.sh"
+				exit 1
+			fi
 			echo "Installing with brew"
 			brew install $(cat $pkg_file)
 		else
